language: node_js

node_js: 10.16

arch: power

env:
  - FOO=foo
  - BAR=bar
  - BAZ=baz
  - 1=1
  - 2=2
  - 3=3
  - 4=4
  - 5=5
  - 6=6
  - 7=7
  - 8=8
  - 9=9
  - 10=10
  - 11=11
  - 12=12

install: skip

script:
- sudo docker info
- sudo docker run hello-world
- git clone https://github.com/travis-ci/travis-build.git
- cd travis-build
- sudo docker build --build-arg GITHUB_OAUTH_TOKEN .
